### ISSUE TITLE
Module build failed: TypeError: Cannot read property 'attrs' of undefined

### ISSUE THREAD

**Issue by lijiliang** [kisenka/svg-sprite-loader#129]
When I build the following mistakes, can help solve?
Module build failed: TypeError: Cannot read property 'attrs' of undefined

**Comment by kisenka** [comment]
@lijiliang could you please create a demo repo with your setup (package.json, webpack.config.js and piece of code) so I can help you?

**Comment by lrojas94** [comment]
@kisenka I get this error if using the inline string way of calling the loader:

`COMMUNITY_DEBATE: require('svg-sprite-loader!../../static/img/debate-create/community-debate.png'),`

log:
```
ERROR in ./~/svg-sprite-loader/lib/loader.js!./front/static/img/debate-create/community-debate.png
Module build failed: TypeError: Cannot read property 'attrs' of undefined
    at SpriteSymbol.get viewBox [as viewBox] (/home/luis/Work/web/node_modules/svg-baker/lib/symbol.js:35:16)
    at stringifySymbol (/home/luis/Work/web/node_modules/svg-sprite-loader/lib/utils/stringify-symbol.js:11:20)
    at runtimeGenerator (/home/luis/Work/web/node_modules/svg-sprite-loader/lib/runtime-generator.js:43:40)
    at svgCompiler.addSymbol.then (/home/luis/Work/web/node_modules/svg-sprite-loader/lib/loader.js:66:23)
 @ ./front/frontapp/constants/icons.const.js 12:22-102
 @ ./front/frontapp/components/debate/create/step-debate-data.comp.js
 @ ./front/frontapp/components/page/debate-create.page.js
 @ ./front/frontapp/containers/body/debate-create.cont.js
 @ ./front/frontapp/containers/body/body.cont.js
 @ ./front/frontapp/containers/body/body-state.cont.js
 @ ./front/frontapp/containers/app/app.cont.js
 @ ./front/frontapp/boot/app.boot.js
```

**Comment by kisenka** [comment]
@lrojas94 the same request - I need demo repo with your setup (package.json, webpack.config.js and piece of your JS and SVG code).

**Comment by lrojas94** [comment]
Package.json:
```
...
   Dependencies: 
   ...
    "svg-sprite-loader": "^3.0.5",
   ...
```

Webpack config:
```
plugins: [
      new SpriteLoaderPlugin(),
      new webpack.optimize.CommonsChunkPlugin({
        name: 'vendor',
        filename: 'frontapp.vendor.src.js',
        minChunks: module => /node_modules/.test(module.resource),
      }),
      new ExtractTextPlugin('../css/frontapp.css'),
    ],
...
loaders: [
{
        test: /\.(svg)$/,
        loader: 'svg-sprite-loader',
        options: {
          name: 'qo-icon__[name]',
          esModule: false,
          extract: true,
        },
      },
]
```

JS Usage:
```
    COMMUNITY_DEBATE: require('svg-sprite-loader!../../static/img/debate-create/community-debate.png'),
```

**Comment by kisenka** [comment]
And your SVG source please

**Comment by lrojas94** [comment]
You mean the icon?

**Comment by kisenka** [comment]
Yep

**Comment by kisenka** [comment]
I mean source code of your SVG image, not of React component.

**Comment by lrojas94** [comment]
I don't have an SVG Image :) I'm using .pngs. Check the image at the bottom (The interrogation mark)

**Comment by kisenka** [comment]
Ah I see, thanks for reporting. It's a bug, try to fix it on this weekend.

**Comment by zmh7057** [comment]
same question 

&& 

SVG Image:

```html
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="30" height="30" viewBox="0 0 30 30">
    <defs>
        <path id="a" d="M10.1 14H0v2h10.1a5.002 5.002 0 0 0 9.8 0H30v-2H19.9a5.002 5.002 0 0 0-9.8 0z"/>
        <mask id="b" width="30" height="10" x="0" y="0" fill="#fff">
            <use xlink:href="#a"/>
        </mask>
    </defs>
    <use fill="none" fill-rule="evenodd" stroke="#20A0FF" stroke-width="4" mask="url(#b)" xlink:href="#a"/>
</svg>

```

![image](https://user-images.githubusercontent.com/7300964/27219632-fd62901a-52b4-11e7-9f94-3edcb9b9f8c4.png)

**Comment by imnot2** [comment]
same question
webpack config
`{
        test: /\.svg$/,
        include: path.resolve('./axis-ui-shared/icons'),
        exclude: path.resolve('./axis-ui-shared/gudstrap'),
        use: [{
            loader: 'svg-sprite-loader',
            options: {
              extract: true,
              spriteFilename: 'sprite-[hash:6].svg'
            }
          },
          'url-loader?limit=1'
        ]
      }`

less file
`background: url('~axis-ui-shared/icons/icon_camera.svg') center top no-repeat;`

**Comment by kraenhansen** [comment]
Same issue

Here is my SVG:
```
<?xml version="1.0" encoding="UTF-8"?>
<svg width="64px" height="30px" viewBox="0 0 64 30" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="Realm-symbols" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="Handle" fill="#9A9BA5">
            <rect id="Bar-3" x="15" y="18" width="34" height="1"></rect>
            <rect id="Bar-2" x="15" y="15" width="34" height="1"></rect>
            <rect id="Bar-1" x="15" y="12" width="34" height="1"></rect>
        </g>
    </g>
</svg>
```

And the Webpack error:

```
ERROR in ./src/client/components/PanelSplitterHandle.svg
Module build failed: TypeError: Cannot read property 'attrs' of undefined
    at SpriteSymbol.get viewBox [as viewBox] (/Users/kraenhansen/Repositories/realm-object-server/realm-dashboard/node_modules/svg-baker/lib/symbol.js:35:16)
    at stringifySymbol (/Users/kraenhansen/Repositories/realm-object-server/realm-dashboard/node_modules/svg-sprite-loader/lib/utils/stringify-symbol.js:11:20)
    at runtimeGenerator (/Users/kraenhansen/Repositories/realm-object-server/realm-dashboard/node_modules/svg-sprite-loader/lib/runtime-generator.js:43:40)
    at svgCompiler.addSymbol.then (/Users/kraenhansen/Repositories/realm-object-server/realm-dashboard/node_modules/svg-sprite-loader/lib/loader.js:66:23)
 @ ./src/client/components/PanelSplitter.tsx 17:32-68
 @ ./src/client/scenes/FxEdit/index.tsx
 @ ./src/client/App.tsx
 @ ./src/client/index.tsx
 @ multi (webpack)-dev-server/client?http://localhost:9000 webpack/hot/dev-server ./src/client/index.tsx
```

**Comment by lavishmantri** [comment]
Is there any update on this? I've been having same problem.

**Comment by Turboconnard** [comment]
same here...

**Comment by Lighttree** [comment]
Same issue using `svgo-loader` after `svg-sprite-loader`:
```
{
  test: /\.svg$/,
  use: ['svg-sprite-loader', 'svgo-loader']
}
```

**Comment by kisenka** [comment]
@Lighttree which OS is used?

**Comment by kisenka** [comment]
@lijiliang 
@lrojas94
@zmh7057 
@imnot2 
@kraenhansen 
@Turboconnard 
@Lighttree 

It will be much faster if some of you guys create a git-repo with reproducible error. I need only related webpack config, package.json, SVG/PNG image and part of code which imports the image.

**Comment by Pines-Cheng** [comment]
Did someone had resolved this problem?

**Comment by Pines-Cheng** [comment]
found the solution.
```javascript
{
        test: /\.(svg)$/i,
        use: ['svg-sprite-loader'],
        include: svgDirs,  
      },
      {
        test: /\.(jpe?g|png|gif|svg)$/i, 
        use: ['url-loader?limit=1024&name=img/[name].[hash].[ext]']
      },
```
remove the `svg` under.

**Comment by kisenka** [comment]
@imnot2 you're using url-loader before sprite-loader, of course it will fail.

**Comment by kisenka** [comment]
Still couldn't reproduce an error, @lijiliang @lrojas94 @zmh7057 @imnot2 @kraenhansen @Turboconnard @Lighttree guys, help me to help you, create a git-repo with reproducible error.

**Comment by imnot2** [comment]
guys

i fix this error when i use svgo-loader before svg-sprite-loader.
my webpack config like below
```javascript
use: [{
                loader: 'svg-sprite-loader',
                options: {
                    extract: true,
                    spriteFilename: outPut + 'icons/sprite-icon.svg'
                }
            }, {
                loader: 'svgo-loader',
                options: {
                    "plugins": [{
                        "cleanupAttrs": true
                    }, {
                        "cleanupEnableBackground": true
                    }, {
                        "cleanupIDs": true
                    }, {
                        "cleanupListOfValues": true
                    }, {
                        "cleanupNumericValues": true
                    }, {
                        "collapseGroups": true
                    }, {
                        "convertColors": true
                    }, {
                        "convertPathData": true
                    }, {
                        "convertShapeToPath": true
                    }, {
                        "convertStyleToAttrs": true
                    }, {
                        "convertTransform": true
                    }, {
                        "mergePaths": true
                    }, {
                        "moveElemsAttrsToGroup": true
                    }, {
                        "moveGroupAttrsToElems": true
                    }, {
                        "removeComments": true
                    }, {
                        "removeDesc": true
                    }, {
                        "removeDimensions": true
                    }, {
                        "removeDoctype": true
                    }, {
                        "removeEditorsNSData": true
                    }, {
                        "removeEmptyAttrs": true
                    }, {
                        "removeEmptyContainers": true
                    }, {
                        "removeEmptyText": true
                    }, {
                        "removeHiddenElems": true
                    }, {
                        "removeMetadata": true
                    }, {
                        "removeNonInheritableGroupAttrs": true
                    }, {
                        "removeRasterImages": true
                    }, {
                        "removeTitle": true
                    }, {
                        "removeUnknownsAndDefaults": true
                    }, {
                        "removeUselessDefs": true
                    }, {
                        "removeUnusedNS": true
                    }, {
                        "removeUselessStrokeAndFill": true
                    }, {
                        "removeXMLProcInst": true
                    }, {
                        "sortAttrs": true
                    }]
                }
            }]
```

**Comment by kisenka** [comment]
@imnot2 could you please provide SVG image which raises an error?

**Comment by imnot2** [comment]
@kisenka 
```javascript
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg width="30px" height="30px" viewBox="0 0 30 30" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <title>Group</title>
    <desc>Created with Sketch.</desc>
    <defs></defs>
    <g id="UI" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="Pending-request-page" transform="translate(-137.000000, -359.000000)" stroke="#000000" stroke-width="0.75">
            <g id="Group" transform="translate(137.000000, 359.000000)">
                <path d="M26.2737964,29.625 C24.7971042,26.5056274 21.5178116,24.2977907 18.1678771,24.261015 L18.1678771,21.0580816 C20.4723622,19.2683017 21.9111787,15.6417056 21.9060638,11.4270238 C21.8991253,7.59614995 18.8024431,4.49479965 14.9897267,4.50316546 C11.1765342,4.50874326 8.08909961,7.61805305 8.09603667,11.4453 C8.1024369,15.6270516 9.54208281,19.2451135 11.834223,21.0387364 L11.834223,24.2633821 C8.51194398,24.2775392 5.20946788,26.4914957 3.72651359,29.625 L1.99161703,29.625 C1.1026396,29.625 0.375,28.8989124 0.375,28.008383 L0.375,1.99161703 C0.375,1.1026396 1.10108757,0.375 1.99161703,0.375 L28.008383,0.375 C28.8973604,0.375 29.625,1.10108757 29.625,1.99161703 L29.625,28.008383 C29.625,28.8973604 28.8989124,29.625 28.008383,29.625 L26.2737964,29.625 Z" id="Combined-Shape"></path>
                <path d="M0.375,1.99161703 L0.375,28.008383 C0.375,28.8978955 1.10162274,29.625 1.99161703,29.625 L28.008383,29.625 C28.8978955,29.625 29.625,28.8983773 29.625,28.008383 L29.625,1.99161703 C29.625,1.10210454 28.8983773,0.375 28.008383,0.375 L1.99161703,0.375 C1.10210454,0.375 0.375,1.10162274 0.375,1.99161703 Z M0.375,1.99161703 C0.375,1.10108757 1.1026396,0.375 1.99161703,0.375 L28.008383,0.375 C28.8989124,0.375 29.625,1.1026396 29.625,1.99161703 L29.625,28.008383 C29.625,28.8989124 28.8973604,29.625 28.008383,29.625 L1.99161703,29.625 C1.10108757,29.625 0.375,28.8973604 0.375,28.008383 L0.375,1.99161703 Z" id="Rectangle" fill-rule="nonzero"></path>
            </g>
        </g>
    </g>
</svg>
```

**Comment by kisenka** [comment]
@imnot2 please update to `svg-sprite-loader@3.1.5`, remove svgo-loader and see is there any errors now? I've added better error reporting in #170
