### ISSUE TITLE
plugin.js error in Jenkins

### ISSUE THREAD

**Issue by janvesel** [kisenka/svg-sprite-loader#140]
We use svg-sprite-loader in AngularJS 1.6 app. On deploy Jenkins builds it and there is an error that gets thrown only when this svg-sprite-loader is included. This error occurs only on Jenkins and not when building it locally.

Configuration of webpack is similar from that in the example. svg-sprite-loader plugin is loaded for extract functionality.

Webpack partial config
```
  const SpriteLoaderPlugin = require('svg-sprite-loader/plugin');
  plugins.push(new SpriteLoaderPlugin());

  loaders.push({
    test: /\.svg$/,
    loader: 'svg-sprite-loader',
    query: {
      extract: true,
      spriteFilename: 'icons-sprite.svg'
    },
    include : `${paths.assets}/icons`
  });
```

Error output in Jankins
```javascript
[91m/app/node_modules/svg-sprite-loader/lib/plugin.js:6
const { NAMESPACE } = require('./config');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/app/node_modules/svg-sprite-loader/plugin.js:1:80)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/app/webpack.config.js:301:30)
    at Module._compile (module.js:413:34)
```

- Node.js version:  v5.12.0
- webpack version: 1.14.0
- svg-sprite-loader version: 3.0.5 
- OS type & version: AlpineLinux 3.6.

**Comment by MatanBobi** [comment]
Upgrading your node version will fix this problem for you..

**Comment by janvesel** [comment]
Thanks.
