### ISSUE TITLE
Prompt error     ERROR in ./icon/right.svg 

### ISSUE THREAD

**Issue by highmind** [kisenka/svg-sprite-loader#145]
webpack ：2.6.1

ERROR in ./icon/right.svg
Module build failed: SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

**Comment by highmind** [comment]
Here is  webpack config  
rules: [
      {
        test: /\.svg$/,
        use:[
          {
            loader:'svg-sprite-loader',
            options:{
              include:path.resolve(__dirname, 'icon')
            }
          },
          'svgo-loader'
        ]
      }

**Comment by kisenka** [comment]
@highmind please provide a minimal setup where I can reproduce this error: package.json, webpack config, SVG file and piece of code which imports the image. You can create a separate git repo or gist.github.com

**Comment by kisenka** [comment]
@highmind ping
