### ISSUE TITLE
Doesn't support SSR (Serverside Rendering)

### ISSUE THREAD

**Issue by dmitrif** [kisenka/svg-sprite-loader#15]
Injection into document.body is not possible during SSR, resulting in failure.

```bash
./sprite.webpack-module:128
  var baseElement = document.getElementsByTagName('base')[0];
                    ^
ReferenceError: document is not defined
    at new Sprite (./sprite.webpack-module:128:21)
    at Object.<anonymous> (/Users/dfarkov/Projects/core/canada-static/node_modules/svg-sprite-loader/lib/web/global-sprite.webpack-module:3:20)
    at Module._compile (module.js:460:26)
    at Object._module3.default._extensions.(anonymous function) [as .webpack-module] (/Users/dfarkov/Projects/core/canada-static/node_modules/webpack-isomorphic-tools/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:218:11)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/dfarkov/Projects/core/canada-static/app/assets/svg/ios-app-store.svg.webpack-module:3:14)
    at Module._compile (module.js:460:26)
```

**Comment by dmitrif** [comment]
Just noticed the custom sprite behaviour possibility. Closing.

**Comment by kisenka** [comment]
@dmitrif you're welcome! Can you contribute custom server-side sprite later?

**Comment by dmitrif** [comment]
Will do! Is there any way to override the GlobalSprite behaviour?

**Comment by dmitrif** [comment]
Will do!

**Comment by kisenka** [comment]
@dmitrif :+1:

**Comment by dmitrif** [comment]
Ended up switching to https://github.com/dmitrif/webpack-svgstore-plugin as it takes a different approach that fit my situation better.

**Comment by kisenka** [comment]
@dmitrif you need ability to generate sprite file to each entry point?
