### ISSUE TITLE
getting issue while using extract-svg-plugin

### ISSUE THREAD

**Issue by swesh** [kisenka/svg-sprite-loader#161]
**I am trying to extract all svg icons and save them as an SVG bundle (in order to load them on page load).
I'm using below configuration in my webpack.**
from here https://github.com/kisenka/svg-sprite-loader/issues/23

```
var ExtractSVGPlugin = require('svg-sprite-loader/lib/extract-svg-plugin');

module.exports = {
  module: {
    loaders: [
      {
        test: /\.svg$/,
        // extract=true is necessary option
        loader: ExtractSVGPlugin.extract('svg-sprite?extract=true')
      }
    ]
  },

  plugins: [
    new ExtractSVGPlugin('test.svg') // placeholders is not supported yet
  ]
};
```

```
node_modules\extract-text-webpack-plugin\index.js:221
return [this.loader(options)]
^

TypeError: this.loader is not a function
at ExtractSVGPlugin.ExtractTextPlugin.extract (node_modules\extract-text-webpack-plugin\index.js:221:15)
at Object. (config\webpack.config.dev.js:191:28)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object. (D:\Miral\miral-FE\scripts\start.js:31:16)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.runMain (module.js:604:10)
```

**Error is thrown from in extract-text-webpack-plugin.**

**Comment by kisenka** [comment]
@swesh please fill carefully the [issue template](https://github.com/kisenka/svg-sprite-loader/issues/new), it contains useful information for me. I have no time to investigate your problem for myself.

**Comment by swesh** [comment]
Updated

**Comment by kisenka** [comment]
@swesh **Please tell us about your environment:**

- Node.js version: ?
- webpack version: ?
- svg-sprite-loader version: ? 
- OS type & version: ?

**How code which import SVGs looks like? Provide an example**

**Comment by swesh** [comment]
Node v6.11.1
webpack 2
svg-sprite-loader version:3.0.2
on windows 7

**Comment by kisenka** [comment]
@swesh How code which import SVGs looks like? Provide an example.

**Comment by swesh** [comment]
```
const ExtractSVGPlugin = require('svg-sprite-loader/lib/extract-svg-plugin');
const extractSVG = new ExtractSVGPlugin('','test.svg','');
module.exports = {
module: {
    strictExportPresence: true,
    rules: [
    {
        test: /\.svg$/,
        include: "/src/svg/svgs",
        loader: extractSVG.extract('svg-sprite?extract=true')
      },
],
},
plugins: [
extractSVG
],
}
```

**Comment by kisenka** [comment]
There is no `svg-sprite-loader/lib/extract-svg-plugin` in 3.* versions of loader. Maybe you missed [migration guide](https://github.com/kisenka/svg-sprite-loader/blob/master/2.0.md)?

**Comment by kisenka** [comment]
@swesh ping

**Comment by kisenka** [comment]
@swesh ping, still actual?
