### ISSUE TITLE
svg-sprite-loader on React SSR

### ISSUE THREAD

**Issue by kedmyster** [kisenka/svg-sprite-loader#175]
**Do you want to request a feature, report a bug or ask a question?**
Ask a question

**What is the current behavior?**
Can't setup svg-sprite-loader correctly with React SSR, following this [https://github.com/kisenka/svg-sprite-loader/tree/master/examples/server-side-rendering](url), when trying to run the server, I'm getting `ReferenceError: React is not defined`.

**What is the expected behavior?**

**If the current behavior is a bug, please provide the steps to reproduce, at least part of webpack config with loader configuration and piece of your code.**
As mentioned above, just followed the `server-side-rendering` example under my project.

**The best way is to create repo with minimal setup to demonstrate a problem (package.json, webpack config and your code).**
**It you don't want to create a repository - create a [gist](http://gist.github.com) with multiple files**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please tell us about your environment:**

- Node.js version: 6.9.1
- webpack version: 2.6.1
- svg-sprite-loader version: ?3.1.6
- OS type & version: Windows 10

**Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)**
___\static\img\icon-down.svg:3
React.createElement(
^

ReferenceError: React is not defined
    at Object.<anonymous> (___/static/img/icon-down.svg:1:1)
    at Module._compile (module.js:570:32)
    at loader (___\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (___\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (___/src/modules/Html.jsx:2:1)
    at Module._compile (module.js:570:32)
    at loader (___\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .jsx] (___\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn node ENOENT
    at notFoundError (___\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (___\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (___\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by kisenka** [comment]
@kedmyster please create a repo with reproducible error

**Comment by kisenka** [comment]
@kedmyster ping

**Comment by kisenka** [comment]
@kedmyster @mascardoso this is not svg-sprite-loader, but try to add following in your webpack config:

```js
plugins: [
  new webpack.ProvidePlugin({
    "React": "react",
  })
]
```

**Comment by mascardoso** [comment]
@kisenka sorry it's not working ;(. Our project for SSR loads first `babelrc` config. I can see the sprite but not when initially the app starts. Only after reloading it.

**Comment by kisenka** [comment]
@mascardoso the same request: demo repo with minimal code where I can reproduce the error.

**Comment by mascardoso** [comment]
I understand. It will take some time since the project is relatively big. Thanks @kisenka.

**Comment by mascardoso** [comment]
@kisenka I made it work by adding this plugin https://github.com/taddei/babel-plugin-transform-strip-svg-sprite.

**Comment by kisenka** [comment]
@kedmyster ping, still actual?
@mascardoso could you please create a repo?
