### ISSUE TITLE
Module build failed: TypeError: Must be an object

### ISSUE THREAD

**Issue by pwalczyszyn** [kisenka/svg-sprite-loader#18]
I'm trying to use `svg-sprite-loader` but I'm getting following error. Any idea what could be the reason for this?

I'm using webpack also with Babel and ES6.

```
ERROR in ./~/svg-sprite-loader!./src/assets/icons/image.svg
Module build failed: TypeError: Must be an object
    at exports.objectToAttrString (/PATH_TO_MY_PROJECT/node_modules/svg-sprite-loader/lib/utils.js:6:11)
    at SVGDocument.toString (/PATH_TO_MY_PROJECT/node_modules/svg-sprite-loader/lib/svg-document.js:29:18)
    at Object.module.exports (/PATH_TO_MY_PROJECT/node_modules/svg-sprite-loader/index.js:47:17)
```

**Comment by kisenka** [comment]
@pwalczyszyn usually it happens when loader trying to process unsupported content (e.g. from url loader). What loaders in your configuration affects SVG files?

**Comment by pwalczyszyn** [comment]
@kisenka thank you :) That was an issue, I had another loader configured that was messing around with SVGs.
