### ISSUE TITLE
spriteModule not working

### ISSUE THREAD

**Issue by omRm** [kisenka/svg-sprite-loader#200]
**Do you want to request a feature, report a bug or ask a question?**
bug / feature request

**What is the current behavior?**

importing my own spriteModule.js throws compilation errors.

**What is the expected behavior?**
we should be able to load the sprite.js and its dependencies.

**If the current behavior is a bug, please provide the steps to reproduce, at least part of webpack config with loader configuration and piece of your code.**

webpack loader

`        use: [
          'svg-sprite-loader?spriteModule='+path.resolve('./src/lib/sprite.js'),
          'svgo-loader',
        ],
`

Error
`SyntaxError: Unexpected token import
[1]     at createScript (vm.js:56:10)
[1]     at Object.runInThisContext (vm.js:97:10)
[1]     at Module._compile (module.js:542:28)
[1]     at Object.Module._extensions..js (module.js:579:10)
[1]     at Module.load (module.js:487:32)
[1]     at tryModuleLoad (module.js:446:12)
[1]     at Function.Module._load (module.js:438:3)
[1]     at Module.require (module.js:497:17)`

**If this is a feature request, what is motivation or use case for changing the behavior?**

creating a own sprite.js just to pass some options may too much ?
we need to remove/customize attributes in the svg element, e.g

`style="position: absolute; width: 0; height: 0" id="__SVG_SPRITE_NODE__"`

need to change due to accessibility reasons. Maybe it would be easiert to be able to just pass the
config file into the loader options ?

**Please tell us about your environment:**

- Node.js version: v6.11.2
- webpack version: ? 2.7.0
- svg-sprite-loader version:  3.2.6
- OS type & version: ? Windows 7

**Comment by kisenka** [comment]
@omRm sorry for the delay, could you please create a repo where I can reproduce described error? Because by default transpiled code is used - https://github.com/kisenka/svg-sprite-loader/blob/master/lib/config.js#L58

**Comment by omRm** [comment]
Yes, the sprite.build you export is transpiled, but when pointing to my own sprite module i get an error.
I forgot to post my spritemodule.js

even if i only import the sprite module and export it right away, i get the error. Maybe im doing something wrong ?

the sprite.js i forgot to post
```
import Sprite from 'svg-sprite-loader/runtime/sprite';     
export default Sprite;
```

more elaborate error

```
D:\...\node_modules\svg-sprite-loader\runtime\sprite.js:1
(function (exports, require, module, __filename, __dirname) { import Sprite from 'svg-baker-runtime/src/sprite';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\workspace\SON\render-service\dist\server\server.bundle.js:9688:18)
    at __webpack_require__ (D:\workspace\SON\render-service\dist\server\server.bundle.js:20:30)
    at Object.<anonymous> (D:\workspace\SON\render-service\dist\server\server.bundle.js:92:15)
    at __webpack_require__ (D:\workspace\SON\render-service\dist\server\server.bundle.js:20:30)
    at Object.defineProperty.value (D:\workspace\SON\render-service\dist\server\server.bundle.js:9221:73)
    at __webpack_require__ (D:\workspace\SON\render-service\dist\server\server.bundle.js:20:30)
    at Object.defineProperty.value (D:\workspace\SON\render-service\dist\server\server.bundle.js:150:26)
```


i will be able to create a repo sometime this week!

**Comment by kisenka** [comment]
Try to import transpiled sprite in your code:

```js
import Sprite from 'svg-sprite-loader/runtime/sprite.build'; 
```

**Comment by omRm** [comment]
Yes, this does work. but is there a way to set id and style from here ?
calling the constructor does not work

**Comment by kisenka** [comment]
Nope, but you can instantiate sprite class by your own:

```js
import BrowserSprite from 'svg-baker-runtime/browser-sprite'; // <- transpiled

const sprite = new BrowserSprite({
  attrs: {
    id: 'MY_SUPER_ID',
    style: 'border: 1px solid red'
  }
});

document.addEventListener('DOMContentLoaded', function() {
  sprite.mount(document.body, true);
});

export default sprite;
```

**Comment by omRm** [comment]
Rendering this server side should not work, right ?

**Comment by kisenka** [comment]
No, but for SSR you can use plain sprite `svg-baker-runtime/sprite`. Tell me what you want to do :)

**Comment by omRm** [comment]
We use SSR and need to be in full controll of the HTML output.
right now the html output  contains

id="__ SVG_SPRITE_NODE __" and a style="position: absolute; width: 0; height: 0"

we need to change id and remove style.

**Comment by kisenka** [comment]
Have you seen [server side rendering example](https://github.com/kisenka/svg-sprite-loader/tree/master/examples/server-side-rendering)?

Also you can check [runtime which](https://github.com/kisenka/svg-sprite-loader/blob/master/runtime/sprite.js) uses when `target: 'node'` is set in webpack config. You can copy-paste it (replace `svg-baker-runtime/src/sprite` with `svg-baker-runtime/sprite`) and configure like you want.

**Comment by omRm** [comment]
Server side rendering part is working great, but changing id and style is not. 
Setting the HTML output in the Components where svgs are rendered is no option for me.

i also feel like importing svg-beaker runtime to control what svg-sprite-loader should be doing is not
a correct way, and leads to much bloated code.

i think we could close this issue and i would open up a feature request if you'd like

**Comment by kisenka** [comment]
I understand you, thanks for idea. It's minor for me, but still important.

**Comment by omRm** [comment]
No Problem, i appreciate the concern !

maybe something like this would help ?
we already have a direct configuration for symbolID.
```js
 loader: 'svg-sprite-loader',
            options: {
             svgId: 'mysvgID',
             svgClass: 'svgClass',
             svgStyle: 'border: 1px solid red'
            }
```
or custom attributes ?

**Comment by kisenka** [comment]
Technically I need to use some placeholder in runtime code (something like `new BrowserSprite(__OPTIONS__)`) and then replace it in loader runtime generator.

**Comment by omRm** [comment]
Yes, i think that will do

**Comment by davidpelayo** [comment]
Any progress on this?
