### ISSUE TITLE
custom-runtime-generator example fails to build

### ISSUE THREAD

**Issue by sentience** [kisenka/svg-sprite-loader#206]
**Do you want to request a feature, report a bug or ask a question?**

Report a bug.

**What is the current behavior?**

Building the examples failed with an error: Exit status 2. I have narrowed this down to an error building the custom-runtime-generator example.

**What is the expected behavior?**

Building the examples with `npm run build:examples` should run successfully.

**If the current behavior is a bug, please provide the steps to reproduce, at least part of webpack config with loader configuration and piece of your code.**

```
$ node node_modules/webpack/bin/webpack.js --config examples/custom-runtime-generator/webpack.config.js
Hash: 6ad5d3d4a50a10c94dbb
Version: webpack 3.8.1
Time: 226ms
  Asset     Size  Chunks             Chunk Names
main.js  2.78 kB       0  [emitted]  main
   [0] ./main.jsx 310 bytes {0} [built] [failed] [1 error]

ERROR in ./main.jsx
Module build failed: TypeError: query.substr is not a function
    at Object.parseQuery (/Users/kyank/code/svg-sprite-loader/node_modules/loader-utils/lib/parseQuery.js:12:11)
    at Object.module.exports (/Users/kyank/code/svg-sprite-loader/node_modules/babel-loader/lib/index.js:104:35)
```

**Please tell us about your environment:**

- Node.js version: 7.9.0
- webpack version: 3.8.1
- svg-sprite-loader version: 3.4.1 (89c0bdd8218ae0a6963eab1c146bf4903afb1ca7)
- OS type & version: macOS 10.13 (High Sierra)

**Comment by kisenka** [comment]
@sentience cannot reproduce, could you please create repo with minimal setup to demonstrate a problem (package.json, webpack config, SVG image and piece of your code). If you don't want to create a repository - you can create a [gist](http://gist.github.com) with multiple files.

**Comment by kisenka** [comment]
@sentience still actual?
