### ISSUE TITLE
make it server side renderable

### ISSUE THREAD

**Issue by goldensunliu** [kisenka/svg-sprite-loader#22]
trying to server side render my project with svg-sprite-loader returns me exceptions:
```
[ReferenceError: document is not defined]
ReferenceError: document is not defined
    at new o (/Users/sliu/workplace/customer-web/deploy/assets/webpack:/~/svg-sprite-loader/lib/web/sprite.js:127:1)
    at Object.exports.modules.846 (/Users/sliu/workplace/customer-web/deploy/assets/webpack:/~/svg-sprite-loader/lib/web/global-sprite.js:2:1)
    at e (/Users/sliu/workplace/customer-web/deploy/assets/webpack:/webpack/bootstrap 5a43d80279dec3251221:25:1)
    at
```

`down-caret.svg` is one of the svg I am trying to load using the loader
```
TypeError: r.add is not a function
    at Object.exports.modules.926 (/Users/sliu/workplace/customer-web/deploy/assets/webpack:/src/images/svg/down-caret.svg:4:1)
    at e (/Users/sliu/workplace/customer-web/deploy/assets/webpack:/webpack/bootstrap 5a43d80279dec3251221:25:1)
    at [object Object].e.exports.NewSegmentButton.t.createClass.render (/Users/sliu/workplace/customer-web/deploy/assets/webpack:/src/scripts/components/customer/EndUserList/NewSegmentButton.coffee:26:18)
    at [object Object].m._renderValidatedComponentWithoutOwnerOrContext (/Users/sliu/workplace/customer-web/deploy/assets/webpack:/~/react/lib/ReactCompositeComponent.js:587:1)
```

**Comment by kisenka** [comment]
@goldensunliu try this https://github.com/kisenka/svg-sprite-loader/issues/19#issuecomment-168149953

**Comment by kisenka** [comment]
@goldensunliu does it helps?

**Comment by goldensunliu** [comment]
yeah that makes sense! We actually using https://github.com/sairion/svg-inline-loader for now
