### ISSUE TITLE
3.5.0 installation fails

### ISSUE THREAD

**Issue by sqal** [kisenka/svg-sprite-loader#224]
**Do you want to request a feature, report a bug or ask a question?**
Bug

**What is the current behavior?**
I cannot install the last version of svg-sprite-loader

Logs:

```
svg-sprite-loader@3.5.0 postinstall C:\dev\xyz\node_modules\svg-sprite-loader
> yarn env webpack-3

yarn env v1.0.2
$ node scripts/select-env "webpack-3"
module.js:473
      throw err;
      ^

Error: Cannot find module 'C:\dev\xyz\node_modules\svg-sprite-loader\scripts\select-env'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:453:25)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm WARN Error: EPERM: operation not permitted, scandir 'C:\dev\xyz\node_modules\fsevents\node_modules\dashdash\node_modules'
npm WARN  { Error: EPERM: operation not permitted, scandir 'C:\dev\xyz\node_modules\fsevents\node_modules\dashdash\node_modules'
npm WARN   stack: 'Error: EPERM: operation not permitted, scandir \'C:\\dev\\xyz\\node_modules\\fsevents\\node_modules\\dashdash\\node_modules\'',
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'C:\\dev\\xyz\\node_modules\\fsevents\\node_modules\\dashdash\\node_modules' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svg-sprite-loader@3.5.0 postinstall: `yarn env webpack-3`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the svg-sprite-loader@3.5.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pc\AppData\Roaming\npm-cache\_logs\2017-12-08T12_29_25_133Z-debug.log
```

**Please tell us about your environment:**

- Node.js version: 8.5.0
- NPM version: 5.5.1
- webpack version: 3.10.0
- svg-sprite-loader version: 3.5.0 
- OS type & version:  Windows 10 x64

**Comment by kisenka** [comment]
@sqal just published `svg-sprite-loader@3.5.1` with fix.

**Comment by sqal** [comment]
@kisenka It works now, thanks for the quick fix! :)

**Comment by cho-is** [comment]
blazing fast, kudos for it

**Comment by kisenka** [comment]
@sqal quick report - quick fix! :)
