### ISSUE TITLE
Error in parsing SVG: Non-whitespace before first tag.

### ISSUE THREAD

**Issue by JamesJefferyUK** [kisenka/svg-sprite-loader#236]
I'm getting the following error:

```
WARNING in ./src/assets/paw.svg
svg-sprite-loader exception. Some loaders will be applied after svg-sprite-loader in extract mode
 @ ./src/index.ts 2:14-41
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/index.ts

WARNING in ./src/assets/triangle.svg
svg-sprite-loader exception. Some loaders will be applied after svg-sprite-loader in extract mode
 @ ./node_modules/css-loader!./node_modules/postcss-loader/lib!./src/sss/base.sss 6:5369-5402
 @ ./src/sss/base.sss
 @ ./src/index.ts
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/index.ts

WARNING in ./src/assets/brown-dog.svg
svg-sprite-loader exception. Some loaders will be applied after svg-sprite-loader in extract mode
 @ ./node_modules/css-loader!./node_modules/postcss-loader/lib!./src/sss/base.sss 6:5434-5468
 @ ./src/sss/base.sss
 @ ./src/index.ts
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/index.ts

ERROR in ./src/assets/paw.svg
Module build failed: Error: Error in parsing SVG: Non-whitespace before first tag.
Line: 0
Column: 1
Char: e
    at /Users/god/Desktop/s3-lander/node_modules/svgo-loader/index.js:36:14
    at <anonymous>
 @ ./src/index.ts 2:14-41
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/index.ts

ERROR in ./src/assets/triangle.svg
Module build failed: Error: Error in parsing SVG: Non-whitespace before first tag.
Line: 0
Column: 1
Char: e
    at /Users/god/Desktop/s3-lander/node_modules/svgo-loader/index.js:36:14
    at <anonymous>
 @ ./node_modules/css-loader!./node_modules/postcss-loader/lib!./src/sss/base.sss 6:5369-5402
 @ ./src/sss/base.sss
 @ ./src/index.ts
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/index.ts

ERROR in ./src/assets/brown-dog.svg
Module build failed: Error: Error in parsing SVG: Non-whitespace before first tag.
Line: 0
Column: 1
Char: e
    at /Users/god/Desktop/s3-lander/node_modules/svgo-loader/index.js:36:14
    at <anonymous>
 @ ./node_modules/css-loader!./node_modules/postcss-loader/lib!./src/sss/base.sss 6:5434-5468
 @ ./src/sss/base.sss
 @ ./src/index.ts
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/index.ts

ERROR in ./src/sss/base.sss
Module build failed: ModuleBuildError: Module build failed: Error: Error in parsing SVG: Non-whitespace before first tag.
Line: 0
Column: 1
Char: m
    at /Users/god/Desktop/s3-lander/node_modules/svgo-loader/index.js:36:14
    at <anonymous>
    at runLoaders (/Users/god/Desktop/s3-lander/node_modules/webpack/lib/NormalModule.js:195:19)
    at /Users/god/Desktop/s3-lander/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/god/Desktop/s3-lander/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/god/Desktop/s3-lander/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/god/Desktop/s3-lander/node_modules/svgo-loader/index.js:36:5
    at <anonymous>
 @ ./src/sss/base.sss
 @ ./src/index.ts
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/index.ts
```

The `triangle.svg` file is:

```
<svg xmlns="http://www.w3.org/2000/svg" width="776" height="78" viewBox="0 0 776 78">
  <polygon fill="#FFF" fill-rule="evenodd" points="721 0 1109 78 333 78" transform="rotate(180 554.5 39)"/>
</svg>
```

I've ran the following command to test if it's an `svgo` issue but that runs fine, which suggests that maybe its an issue with this library?

```

node_modules/svgo/bin/svgo src/assets/triangle.svg -o src/assets/triangle.min.svg [8d23h1m]✭ M ✖

triangle.svg:
Done in 14 ms!
0.196 KiB - 35.3% = 0.127 KiB
```

Node: 8.9.0
Webpack: 3.10.0

**Comment by kisenka** [comment]
It means that svg-sprite-loader should applies __after__ svgo-loader
