### ISSUE TITLE
`svg-sprite-loader` seems to handle loader conditions incorrectly

### ISSUE THREAD

**Issue by thasmo** [kisenka/svg-sprite-loader#246]
**Do you want to request a feature, report a bug or ask a question?**
Bug

**What is the current behavior?**
Using a function on an `include` condition throws an error `Module build failed: TypeError: test.test is not a function`.

**What is the expected behavior?**
`svg-sprite-loader` should handle `include` and `exclude` conditions of type `function` correctly.

**Please tell us about your environment:**
- Node.js version: 9.5.0
- webpack version: 3.11.0
- svg-sprite-loader version: 3.6.2
- OS type & version: Windows 10 Pro 64-bit

**Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)**
```sh
Module build failed: TypeError: test.test is not a function
    at Object.matchPart (P:\project\node_modules\webpack\lib\ModuleFilenameHelpers.js:151:15)
    at matchObject (P:\project\node_modules\webpack\lib\ModuleFilenameHelpers.js:159:29)
    at rules.filter (P:\project\node_modules\svg-sprite-loader\lib\utils\get-matched-rules.js:15:9)
    at Array.filter (<anonymous>)
    at getMatchedRules (P:\project\node_modules\svg-sprite-loader\lib\utils\get-matched-rules.js:12:30)
    at Object.loader (P:\project\node_modules\svg-sprite-loader\lib\loader.js:27:24)
 @ ./assets/components/icon/index.ts 7:0-43
 @ ./assets/main.ts
 @ multi ./assets/main.ts
```
It seems that the problem is somewhere [around here](https://github.com/kisenka/svg-sprite-loader/blob/ace9f47f90e4baee29183cf5b393e0807371cf70/lib/utils/get-matched-rules.js#L13), where `rule.test` is checked to be a function, but `rule.include` and `rule.exclude` are not tested, which cause problems in `webpack\lib\ModuleFilenameHelpers.js` lines 142-162.

@kisenka, if you need anymore information feel free to ping me. 👍

**Comment by thasmo** [comment]
My rules look like this:
```js
{
    test: /\.svg$/,
    include: (path) => return true;
    use: [...loaders]
}
```

**Comment by kisenka** [comment]
@thasmo could you please make a PR?
