### ISSUE TITLE
Can't run 'yarn bootstrap' because Cannot find module 'shelljs'

### ISSUE THREAD

**Issue by jarodtaylor** [kisenka/svg-sprite-loader#303]
**Do you want to request a feature, report a bug or ask a question?**
Bug when trying to pull down repo to contribute.

**What is the current behavior?**
After forking the repo and pulling it down locally, when I attempt to `yarn bootstrap` I get the following:
![image](https://user-images.githubusercontent.com/362248/44884896-937df980-ac83-11e8-9cf8-aed55906fa1e.png)

**What is the expected behavior?**
It should install the dependencies needed.

**Please tell us about your environment:**

- Node.js version: 8.2.1
- webpack version: 2.2.1
- OS type & version: OS X Sierra

**Comment by jarodtaylor** [comment]
Okay, so I tried the following:

1. Switched to node version 6.14.4
2. Ran `npm install`
3. Then ran `npm run bootstrap`

This was the result:

![image](https://user-images.githubusercontent.com/362248/44937042-f54e6a00-ad3c-11e8-9803-94cd3af49b18.png)

**Comment by jarodtaylor** [comment]
So, after inspecting the `script/bootstrap.js` it looks like the [following line](https://github.com/kisenka/svg-sprite-loader/blob/master/scripts/bootstrap.js#L24) is what's killing the script. It looks like `envToSelect.name` returns `undefined`. If I remove `name`:

```
exec(`node ${projectDir}/scripts/select-env ${envToSelect}`);
```

It finishes.

**Comment by kisenka** [comment]
@jarodtaylor sorry for delay, I've updated bootstrap script, please check

**Comment by jarodtaylor** [comment]
```bash
➜  svg-sprite-loader git:(master) ✗ yarn bootstrap
yarn run v1.7.0
$ node scripts/bootstrap
warning npm-shrinkwrap.json found. This will not be updated or respected. See https://yarnpkg.com/en/docs/migrating-from-npm for more information.
[1/5] Validating package.json...
[2/5] Resolving packages...
(node:11669) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > babel-loader@6.4.1" has incorrect peer dependency "webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc".
[5/5] Building fresh packages...
success Saved lockfile.
husky
setting up hooks
done

[1/4] Resolving packages...
[2/4] Fetching packages...
(node:11714) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
webpack-1 env installed
[1/4] Resolving packages...
[2/4] Fetching packages...
(node:12227) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
webpack-2 env installed
[1/4] Resolving packages...
[2/4] Fetching packages...
(node:12231) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
webpack-3 env installed
[1/4] Resolving packages...
[2/4] Fetching packages...
(node:12233) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
webpack-4 env installed
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/Users/jarodtaylor/Desktop/svg-sprite-loader/env/webpack-3/node_modules/enhanced-resolve/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at packagesToLink.forEach (/Users/jarodtaylor/Desktop/svg-sprite-loader/scripts/select-env.js:24:19)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/jarodtaylor/Desktop/svg-sprite-loader/scripts/select-env.js:21:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
✨  Done in 35.80s.
```
