### ISSUE TITLE
Unexpected token windows

### ISSUE THREAD

**Issue by phun-ky** [kisenka/svg-sprite-loader#65]
I've used this loader with great success on Linux/MacOS, but when I try to use it on Windows, I get this type of error message on all my SVG files:

    ERROR in ./src/client/images/icons/ic_description_black_48px.svg
    Module parse failed: C:\Users\<path>\src\client\images\icons\ic_description_black_48px.svg Unexpected token (1:0)
    You may need an appropriate loader to handle this file type.
    SyntaxError: Unexpected token (1:0)
        at Parser.pp$4.raise (C:\Users\<path>\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
        at Parser.pp.unexpected (C:\Users\<path>\node_modules\webpack\node_modules\acorn\dist\acorn.js:603:10)
        at Parser.pp$3.parseExprAtom (C:\Users\<path>\node_modules\webpack\node_modules\acorn\dist\acorn.js:1822:12)
        at Parser.pp$3.parseExprSubscripts (C:\Users\<path>\node_modules\webpack\node_modules\acorn\dist\acorn.js:1715:21)
        at Parser.pp$3.parseMaybeUnary (C:\Users\<path>\node_modules\webpack\node_modules\acorn\dist\acorn.js:1692:19)
        at Parser.pp$3.parseExprOps (C:\Users\<path>\node_modules\webpack\node_modules\acorn\dist\acorn.js:1637:21)
        at Parser.pp$3.parseMaybeConditional (C:\Users\<path>\node_modules\webpack\node_modules\acorn\dist\acorn.js:1620:21)
        at Parser.pp$3.parseMaybeAssign (C:\Users\<path>\node_modules\webpack\node_modules\acorn\dist\acorn.js:1597:21)
        at Parser.pp$3.parseExpression (C:\Users\<path>\node_modules\webpack\node_modules\acorn\dist\acorn.js:1573:21)
        at Parser.pp$1.parseStatement (C:\Users\<path>\node_modules\webpack\node_modules\acorn\dist\acorn.js:727:47)
        at Parser.pp$1.parseTopLevel (C:\Users\<path>\node_modules\webpack\node_modules\acorn\dist\acorn.js:638:25)
        at Parser.parse (C:\Users\<path>\node_modules\webpack\node_modules\acorn\dist\acorn.js:516:17)
        at Object.parse (C:\Users\<path>\node_modules\webpack\node_modules\acorn\dist\acorn.js:3098:39)
        at Parser.parse (C:\Users\<path>\node_modules\webpack\lib\Parser.js:902:15)
        at DependenciesBlock.<anonymous> (C:\Users\<path>\node_modules\webpack\lib\NormalModule.js:104:16)
        at DependenciesBlock.onModuleBuild (C:\Users\<path>\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
     @ ./src/client/components/policies/policy/PolicyHistory.jsx 57:33-95

What could be the issue here?

Using `"svg-sprite-loader": "0.0.15",`
npm -v 3.10.3
node -v 6.5.0

**Comment by phun-ky** [comment]
Upgraded to latest version of `svg-sprite-loader`, still have the same issue.

**Comment by kisenka** [comment]
Could you create a test case for this?

**Comment by phun-ky** [comment]
I figured out the issue. It seems that the `include` parameter in the loader (for any loader)  in the config on windows is not so forgiving as on linux/macos. I had in my regexp (test):

    /(images\/.*)\.(svg)$/i

And in my `include`:

    include: [
      path.resolve(srcDir, 'client/images/icons'),
      path.resolve(srcDir, 'client/images/logo')
    ]

Which did not work.

Once I changed to `/\.(svg)$/i` it worked.

**Comment by ophite** [comment]
I have this bug on windows 10, npm 5.4.2, node 8.7, not help /\.(svg)$/i

**Comment by kisenka** [comment]
@ophite usually it's about loaders configuration. Are you sure you configured it properly? Please provide relative part of webpack config.

**Comment by ophite** [comment]
it works in linux/mac and dont work in windows:

{
          test: /\.(svg)$/,
          loader: 'svg-sprite-loader',
          include: [
            `${path.join(rootFolder, 'src/themes/default')}/icons/svg`,
            `${path.join(rootFolder, `src/themes/${themeName}`)}/icons/svg`,
          ],
          options: {
            extract: true,
            spriteFilename: 'theme-sprite.svg',
          },
        },

**Comment by kisenka** [comment]
@ophite try to use `path.resolve` instead of `path.join`

**Comment by ophite** [comment]
@kisenka rootFolder get with `path.resolve`

**Comment by kisenka** [comment]
Try to use `path.resolve` also in include

**Comment by ophite** [comment]
Thanx a lot all works))) Was error with slash in path

**Comment by a526672351** [comment]
Thanx ,use path.resolve instead of path.join , can be solved
